### ISSUE TITLE
file sync bug

### ISSUE THREAD

**Issue by wangweitung** [Alt-er/obsidian-sync-share#17]
iPad turn on the option：setting-daily note-open daily note on startup. (turned off at 10/23)

10/24:
phone creat the daily note and take some notes.

at 10/24 night
open iPad and it automatically creates a new 10/24 daily note with nothing.

then I manually activate sych-share-plugin on ipad.
then I manually activate sych-share-plugin on phone.
the daily note 10/24 on phone  gets lost. only with a blank daily note left.

is this  a sync bug or not?

**Comment by wangweitung** [comment]
or adding an option that  automatically sycn at startup？

**Comment by Alt-er** [comment]
This is not a bug, because the file update depends on the modification time. When the modification time of the same file in different devices is different, the most recently modified one will overwrite the previous data.

If you add a function to automatically run synchronization when starting the plug-in, it seems that the problem cannot be avoided, because the plug-in cannot guarantee that your other plug-ins have not previously created files with the same name when running synchronization.
