### ISSUE TITLE
Sync before closing Obsidian

### ISSUE THREAD

**Issue by onnyyonn** [Alt-er/obsidian-sync-share#21]
Given that syncing only happens at some interval, your most recent changes may not be synced, if you close Obsidian before the sync could take place. Is it possible to force syncing when Obsidian is closed?

There is a similar issue at the obsidian-git repository https://github.com/denolehov/obsidian-git/issues/13 , where they mention that it may be possible with Obsidian API. They have also implemented an alternative "create backup and close" action, which the user can use instead of directly closing the app. Would you be open to implement something similar?

**Comment by Alt-er** [comment]
It is recommended to directly speed up the synchronization frequency, for example: synchronize once every 5-10 seconds.

Automatic synchronization before shutdown is not safe, because synchronization may be very time-consuming, resulting in only part of the synchronization, or obsidian being forcibly closed and synchronization cannot be triggered, etc.

**Comment by onnyyonn** [comment]
Speeding up synchronization frequency has its own issues. It clogs up the git history. But I also understand your reasoning for not implementing sync before closing. Thanks for considering. Feel free to close this issue.
