### ISSUE TITLE
managing all shared webs in one page?

### ISSUE THREAD

**Issue by wangweitung** [Alt-er/obsidian-sync-share#6]
I share 123.md to the web, then I delete 123.md. 
The shared file still keeped in the share folder, I have to delete it in my server manually.
Could there be a page showing all the shared files?so I can delete them there.

another question :  after the 123.md file updated , I have to share it again to get the new link , could there be a permanent link ？

**Comment by Alt-er** [comment]
Yes , if you need to delete a shared file, please delete the sharing record in the `share` panel first, if you have already deleted the note, you can create a new note with the same name, and then you can clean up the sharing record

Each share is a snapshot of the current state of the note, if your note is updated, you will need to re-share it.
If you need to reshare the note, the link will remain unchanged after resharing, this feature is under consideration, we are going to add a function to overwrite the shared record, so that you can reuse the previous link.

**Comment by Alt-er** [comment]
> Could there be a page showing all the shared files?so I can delete them there.

temporarily do not have this function , because of the sharing of records is very much the case , this page needs to consider a lot of things , such as multi-level grouping grouping sorting pagination and other operations , which in the obsidian panel to achieve a more laborious , so it is not done for the moment .

**Comment by wangweitung** [comment]
> Each share is a snapshot of the current state of the note, if your note is updated, you will need to re-share it. If you need to reshare the note, the link will remain unchanged after resharing, this feature is under consideration, we are going to add a function to overwrite the shared record, so that you can reuse the previous link.

hope to see this feature soon. Thanks!

**Comment by wangweitung** [comment]
> 

understood

**Comment by wangweitung** [comment]
> > Could there be a page showing all the shared files?so I can delete them there.
> 
> temporarily do not have this function , because of the sharing of records is very much the case , this page needs to consider a lot of things , such as multi-level grouping grouping sorting pagination and other operations , which in the obsidian panel to achieve a more laborious , so it is not done for the moment .

understood
